/** Possible trajectory types: straight, spiral, sideToSide */
export const levels = [
  {
    level: 1,
    text: {
      header: 'Level 1',
      subHeader: 'Now the space battle will begin!',
    },
    waves: [
      {
        time: 3000,
        enemy: 'small',
        trajectory: 'straight',
        number: 3,
        enemyDelay: 1500,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 8000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 5,
        enemyDelay: 200,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 10000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 5,
        enemyDelay: 200,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 14000,
        enemy: 'small',
        trajectory: 'straight',
        number: 20,
        enemyDelay: 0,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 19000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 20,
        enemyDelay: 150,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 22000,
        enemy: 'small',
        trajectory: 'straight',
        number: 1,
        enemyDelay: 0,
        shotCooldown: 1200,
        lives: 5,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 28000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 5,
        enemyDelay: 200,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 32000,
        enemy: 'small',
        trajectory: 'straight',
        number: 10,
        enemyDelay: 0,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 36000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 40000,
        enemy: 'medium',
        trajectory: 'straight',
        number: 2,
        enemyDelay: 0,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
    ],
  },
  {
    level: 2,
    text: {
      header: 'Level 2',
      subHeader: null,
    },
    waves: [
      {
        time: 5000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 6000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 12000,
        enemy: 'small',
        trajectory: 'straight',
        number: 10,
        enemyDelay: 20,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 17000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 10,
        enemyDelay: 150,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 22000,
        enemy: 'medium',
        trajectory: 'straight',
        number: 3,
        enemyDelay: 0,
        shotCooldown: 1000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 25000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 15,
        enemyDelay: 200,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 29000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 20,
        enemyDelay: 100,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 33000,
        enemy: 'big',
        trajectory: 'straight',
        number: 5,
        enemyDelay: 100,
        shotCooldown: 2500,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 36000,
        enemy: 'small',
        trajectory: 'straight',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 40000,
        enemy: 'medium',
        trajectory: 'spiral',
        number: 2,
        enemyDelay: 200,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
    ],
  },
  {
    level: 3,
    text: {
      header: 'Level 3',
      subHeader: 'Last battle!',
    },
    waves: [
      {
        time: 5000,
        enemy: 'medium',
        trajectory: 'spiral',
        number: 12,
        enemyDelay: 200,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 9000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 10,
        enemyDelay: 50,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 15000,
        enemy: 'small',
        trajectory: 'spiral',
        number: 20,
        enemyDelay: 100,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 20000,
        enemy: 'big',
        trajectory: 'straight',
        number: 1,
        enemyDelay: 100,
        shotCooldown: 1000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 25000,
        enemy: 'medium',
        trajectory: 'sideToSide',
        number: 5,
        enemyDelay: 200,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 30000,
        enemy: 'small',
        trajectory: 'straight',
        number: 10,
        enemyDelay: 100,
        shotCooldown: 2000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 34500,
        enemy: 'big',
        trajectory: 'straight',
        number: 5,
        enemyDelay: 0,
        shotCooldown: 4000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 38000,
        enemy: 'small',
        trajectory: 'straight',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 4000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 42500,
        enemy: 'small',
        trajectory: 'straight',
        number: 4,
        enemyDelay: 500,
        shotCooldown: 4000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 45000,
        enemy: 'small',
        trajectory: 'straight',
        number: 25,
        enemyDelay: null,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 48000,
        enemy: 'medium',
        trajectory: 'spiral',
        number: 2,
        enemyDelay: 500,
        shotCooldown: 5000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 55000,
        enemy: 'medium',
        trajectory: 'straight',
        number: 8,
        enemyDelay: 20,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 59500,
        enemy: 'small',
        trajectory: 'spiral',
        number: 20,
        enemyDelay: 100,
        shotCooldown: 6000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 63700,
        enemy: 'small',
        trajectory: 'spiral',
        number: 20,
        enemyDelay: 100,
        shotCooldown: 6000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 68000,
        enemy: 'big',
        trajectory: 'straight',
        number: 1,
        enemyDelay: 100,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 74000,
        enemy: 'small',
        trajectory: 'sideToSide',
        number: 20,
        enemyDelay: 100,
        shotCooldown: 3000,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 77000,
        enemy: 'small',
        trajectory: 'straight',
        number: 25,
        enemyDelay: null,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 78000,
        enemy: 'small',
        trajectory: 'straight',
        number: 25,
        enemyDelay: null,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 79000,
        enemy: 'small',
        trajectory: 'straight',
        number: 25,
        enemyDelay: null,
        shotCooldown: null,
        lives: 1,
        score: 1,
        startSpawn: false,
        spawned: false,
      },
      {
        time: 82000,
        enemy: 'big',
        trajectory: 'straight',
        number: 5,
        enemyDelay: null,
        shotCooldown: 1000,
        lives: 25,
        score: 1000,
        startSpawn: false,
        spawned: false,
      },
    ],
  },
];